export const types = Object.freeze({
    // Sync
    SONG_FILL: 'SONG_FILL',
    LIKED_SONGS_FILL: 'LIKED_SONGS_FILL',
    RANDOM_SONG_FILL: 'RANDOM_SONG_FILL',
    UPDATE_LIKED_SONGS_FILL: 'UPDATE_LIKED_SONGS_FILL',
    CLEAR_LIKED_SONGS_STORE: 'CLEAR_LIKED_SONGS_STORE',

    // Async
    LIKED_SONGS_FETCH_ASYNC: 'LIKED_SONGS_FETCH_ASYNC',
    SONG_FETCH_ASYNC: 'SONG_FETCH_ASYNC',
    RANDOM_SONG_FETCH_ASYNC: 'SONG_FETCH_ASYNC',
    LIKE_SONG_FETCH_ASYNC: 'LIKE_SONG_FETCH_ASYNC'
});
